version: '3'
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:14.5-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  app:
    image: typeorm-bug
    build:
      context: .
      dockerfile: App.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - CACHE=1 # Toggle this for testing. 1 = enabled, 0 = disabled